### ISSUE TITLE
Wifi connection

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#12]
Hi thanks for a fantastic product.
I have a question about using wifi.
I have problem to connect using SSL.
When I use cable on the same net it works good when booting from an ISO.
I connect to 10.1.0.2 with cable inserted, thats work real good. the net is 192.168.8.X.
But when I connect to the same net without cable I can't connect to the same machine.
I go in to the wifi connect thing and connect.
I can ping 10.1.0.2 but ssl won't connect to the container.
do you thing something with ssl server needs to be restarted?
Strange.

Another question if its ok.
How to you know what machine to connect to open vpn. I mean Expert and Scout. I want to usr more clients on the same oentvpn Server. Is it the certificates? can you explain how to use it? 

Dennis

**Comment by vitaly-kamluk** [comment]
Hi
I guess you meant SSH connection. Could VPN IP adress come in conflict with your WiFi network address? Please confirm that you have successfully connected to WiFi and check your WiFi IP. You should see it with `$ ifconfig wlan0` command. If WiFi IP is on the same subnet (10.1.x.x) then you may have a problem, which has to be resolved by moving to another subnet.  
Btw, you don't need to restart SSH server after connection. It listens on all interfaces on port 22 and shall work automatically regardless of connection type.  
  
As for your other question, if you want to connect more clients you need to generate more openvpn certificates or enable certificate sharing. Please see instructions here: https://github.com/vitaly-kamluk/bitscout/wiki/Basic-Usage#additional-openvpn-users

**Comment by melorium** [comment]
Yes its he SSL connection as long I use cable it Works.
And when I start the iso without cable I can't connect using SSL.
I can ping to 10.1.0.2 from the expert machine but not ssl connect.
I tried a lot of different wireless network. on the same lan as the cable to.
I have cable and the iso image got 192.168.200.10 and it works perfekt, but when I connect to wireless using the same lan I got 192.168.200.15 I can still use ping but not ssl.

I don't know what I'm doing wrong.

I have tried a different openvpn server different client and experts machines.

When I start the iso I use the wifi config tool to connect to wifi and exerting seems ok. 
I can ping both 10.1.0.1 and 10.0.1.3 from the scout machine.

But when i connect using ssl I just got time time out.

Do you have any idea whats going on here ?

Im so angry on my self when I don't find the solution.

Dennis

**Comment by melorium** [comment]
When I use go Container shell it says waiting for container.

What does it mean?

Dennis

**Comment by melorium** [comment]
![skarmklipp 2017-09-05 11 48 43](https://user-images.githubusercontent.com/31001934/30055617-51f401e4-9230-11e7-9075-7626b719db19.png)

**Comment by vitaly-kamluk** [comment]
Dennis, if the management tool shows "Waiting for container.." - it's bad sign. It means the container couldn't start properly.
In this case when you ping 10.1.0.2, the bitscout host replies, but SSH server is down most likely because the container is not running. There may be several reasons and we fixed many of those.
Which version of bitscout are you using? Can you download and build the latest from my github repository before we continue?

Note, that you can copy your ./config directory from your previous build. However, to be safe, delete the ./config/bitscout-build.conf file and run automake.sh again and answer the questions. For your test you can skip building the custom kernel, because it's long process.
If something goes wrong, run ./clean.sh and start building again.

**Comment by melorium** [comment]
aha so when waiting for container is showing something gets wrong?
But when I connect with cable everything works good, bit notes wireless.
As you can see I can connect with ssh a and map nbd (the last pic)
but when I do it wireless I can't connect.
![skarmklipp 2017-09-05 15 22 32](https://user-images.githubusercontent.com/31001934/30063179-16ca79e0-924e-11e7-8c8f-88821bece371.png)


![skarmklipp 2017-09-05 15 13 43](https://user-images.githubusercontent.com/31001934/30062934-338ab668-924d-11e7-823b-de5b3e58be11.png)

![skarmklipp 2017-09-05 15 14 52](https://user-images.githubusercontent.com/31001934/30062942-3b44eed2-924d-11e7-905d-a6b82ae41148.png)
![skarmklipp 2017-09-05 15 13 43](https://user-images.githubusercontent.com/31001934/30062957-4558f6ac-924d-11e7-8ba7-7f79b59995ca.png)

**Comment by melorium** [comment]
Ok i will build a image again and try.
Can I start and stop the container from the iso shell to see whats going on?
And how can I see the status of it on the scout machine?

Dennis

**Comment by melorium** [comment]
Very stupid question is it better to use a 32 bit Ununtu linux?

**Comment by melorium** [comment]
Hi again.
Yesterday I tried to make iso images I'm different machines.
Everything works fine when I'm cabled I can connect using cables. Both internal in my home and I also tried with a friend who lives ver fare away from me. I sent him an iso image and started in his home.
When he use cable it worked perfekt to connect to connect using ssl, and I could mount his disk remote with NBD.
After that he restarted the iso and using wifi in his home. Same adress as I wired connection.
his internal net was 192.168.0.1 there wired have 192.168.0.100 and the wifi was 192.168.0.102.
He mapped up the wifi network and I could ping his host 10.1.0.2. but I could not connect using SSH.
![skarmklipp 2017-09-05 15 14 27](https://user-images.githubusercontent.com/31001934/30098585-c98f930a-92e2-11e7-9469-71243c886776.png)

As you see here this is the windows from the container shell of the iso image.
Is always says waiting for container even when I'm cabled and it works well even if it says waiting for container.

So I don't know what more to du with the wifi thing, I looks like when I start without cable something does not start up good.

I wish I was a better expert :(

Dennis

**Comment by melorium** [comment]
Maybe I'm a dumb ass not understand what I'm doing :(

**Comment by vitaly-kamluk** [comment]
Ok, Dennis, it looks like a bug to me.

As for the message, if you see "Waiting for container..." - it's bad only if you don't see the shell prompt after that. The last screenshot you showed is perfectly normal, the container is up.  

Let me do some tests with WiFi on my side and get back to you soon.

**Comment by melorium** [comment]
Yes Yes thanks a lot.
Im realy impressed by the produkt and I want i using the wifi part to.
I work a lot with IP and routing but maybe I missed something important.
Im very thankful for your help.

**Comment by melorium** [comment]
I would be interesting to see if wifi work normal on your side :)

Dennis

**Comment by melorium** [comment]
Wifi network is important for me beq most people I Sweden din have cable anymore.
Hope you find something.
But probably I did something wrong
Dennis

**Comment by melorium** [comment]
Have you tried wifi yet :)
Im curious about that.

Dennis

**Comment by vitaly-kamluk** [comment]
Hi!
I tried and seems that you are right. There was a problem with wifi manager known as Wicd. It detected and autoconfigured wrong wired network (container bridge interface), which broke connection to the container via vpn. That should have caused symptoms that you observed when connecting via WiFi. I fixed that but tested just on a single system yet. Fixed version is available on github now. Feel free to build and test new ISO!
I will try testing on a second machine tomorrow and if it doesn't work will keep digging.

**Comment by melorium** [comment]
Thanks :):):)

**Comment by melorium** [comment]
Il test a new build soon and report here.

Thanks again

**Comment by melorium** [comment]
Everything works perfekt.
Now wifi works with ssh and all the block commands work perfekt.
Thanks you Camluk your software is Amazing.
Dennis

**Comment by vitaly-kamluk** [comment]
Awesome! So I consider this wifi issue to be resolved now. Please find and report more bugs! :)

**Comment by melorium** [comment]
Yes I will use this product every days so if I find something I tell you.

I also will try to learn a lot more on how to use it the best way.

Thanks a lot again.

Dennis
