### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#18]
Hi again.
I don't want to complain but I always try the news.

When make a build I goes real fast end the result is this.

maybe you don't finish the upload

Dennis and thanks again

![skarmklipp 2018-01-09 19 13 06](https://user-images.githubusercontent.com/31001934/34735895-625f2db6-f571-11e7-915c-d1730d71150f.png)

**Comment by melorium** [comment]
Maybe I missed something?
Is it still the link "git clone --recursive https://github.com/vitaly-kamluk/bitscout" I will use til clone?

My old image created 3 days ago is 1.4 GB and the new image created is 750 MB.

The 1.4 GB image works perfekt :):):):):):):)

Thanks again for everything.

Dennis

**Comment by 1wxyz** [comment]
Hi Dennis

I have tested out with this commit 64b96b1, no problems on my side.
Would you be able to share with us the automake log?

1.4 GB image seems too big to me, even with maximal release and custom kernel, it never exceeds 800MB based on my experience.

**Comment by melorium** [comment]
Hmm ok.
Il try again.
It always was around 750 MB, but after the very very good uefi fix it was around 1.4 GB and works perfekt.
But after the new release with optimized things it was 700 mb.
😊
Il send you the log when im home again:
Can i use 17.10 when i make it?
Dennis

Skickat från min iPhone

**Comment by melorium** [comment]
dumb question but where is that log located?

**Comment by melorium** [comment]
Hi again I have some more questions.
If I want to create a user in the host not in container in a script.
You added user "user" without a password in container. If I want to do that even in the the host where can I put that in the script?

And if I want to install additional software in the host how can I know if I install it in container or in the host.

Im running Grr Rapid Responce to in the image to explore the volumes and I work good if i manipulate the system from the booted ISO but I want to have in built in during the iso creation.

I enabled 2 SSH ports one redirected to container and the other to the root shell.

In the root shell I mount the disk and using GRR to explore the disks system after I mount them in RO mode.

Is that a good idea?

or should I run everything in the container?

Do you think GRR is a good utility or do you have any better frameworks?

Im trying to develop the ISO beq I think it it very very good in Remote Forensics manner.

Bitscout is the best solution I ever seen and im ver impressed of your skills there.

Hope you can explain host and container a lil for me.

THANKS Again Vitaly. You are the best.

Dennis

**Comment by vitaly-kamluk** [comment]
Hey, Dennis,
Sorry for slow response lately.
We have added some changes that should optimize rebuilding process and decrease volume of network downloaded data during ISO build.
This new build works on several systems on our side. Could you check again on your side? I recommend to make a fresh build in new directory.
Note, that today we added feature to create automake log. You can find the log in the same directory after you build your ISO. The file is called automake.log. If you have troubles with build - please upload us this file.
As for your other questions - let me answer separately once we solve your build problem.

**Comment by melorium** [comment]
Hi again.
I made a new one using 17.10 desktop today but I also tried 16.04 desktop.
[automake.log](https://github.com/vitaly-kamluk/bitscout/files/1631204/automake.log)
But its no problem for me right now im using the old build.
But of course I want everything to work.
I got the same pic when I boot vmlinux not found.

Dennis :)

**Comment by vitaly-kamluk** [comment]
Hi Dennis,
Thank you for sharing, your build log helped to find the bug. It turns our we didn’t test the build with custom kernel (with kernel write blocker).

I have just committed a fix for that issue. Please try it and let us know when you got a moment!

**Comment by melorium** [comment]
Now it works perfekt again.
Thanks again you are the best.
Now its alot of smaller than before and it boot with everything-

**Comment by vitaly-kamluk** [comment]
Hello Dennis,
I think it’s nice idea to optionally include GRR on the ISO. It can be either server or the agent. 
I will add this to our TODO list.

Regards,
Vitaly

**Comment by melorium** [comment]
Hi again Vitaly.
I have a question about autotest.sh.
Is it a script for just testing the ISO or what are the meaning with it?
Im just cowries?

Dennis

**Comment by melorium** [comment]
Curious haha wrong spell

**Comment by vitaly-kamluk** [comment]
Autotest.sh is a script that makes sure that some essential parts of your new ISO are in place, that system boots normally with ssh running in the guest container. It actually boots a temporary vm using qemu and automates the test. Depending on you CPU it make take about a minute to do full test. It is useful for bitscout developers. We want to make sure that every commit we make doesn’t break something important.
