### ISSUE TITLE
how to install !  #step by step

### ISSUE THREAD

**Issue by jackhopkins96** [vitaly-kamluk/bitscout#2]
Hi dear 

How to install this program ? pleas get me movie file how to install or put in text file 

thank you..

**Comment by vitaly-kamluk** [comment]
Hi!
Thanks for your suggestion. There you go: https://www.youtube.com/watch?v=knA0NS9tWsY
Also, simple instructions explained here: https://github.com/vitaly-kamluk/bitscout/wiki
