### ISSUE TITLE
Automake OpenVPN Input Issue

### ISSUE THREAD

**Issue by unstatusthequo** [vitaly-kamluk/bitscout#24]
I am attempting to input the OpenVPN settings and am running into an issue. [REDACTED] is a valid IP of my OpenVPN server. Any thoughts on what's going on or how to correct it?

`Please choose option number:
 1. compact - minimal size, less tools and drivers.
 2. normal - includes most common forensic tools, drivers, etc.
 3. maximal - includes maximum of forensic tools and frameworks.
 Your choice (1|2|3): 3
If you are going to deal with badly unmounted filesystems, software RAID or LVM, it is recommended to apply kernel write-blocker patch for extra care of the evidence. However, please note that it may take 3-4 hours to rebuild the kernel on a single core CPU.
Would you like to build and use kernel with write-blocker? [Y/n]: n
scripts/welcome.sh: line 96: ${choice^}: bad substitution
To use bitscout remotely you will need a VPN server.
Please enter your designated VPN server protocol (udp/tcp), host and port. You can change it later.
Examples:
 udp://127.0.0.1:2222
 tcp://myvpnserver:8080
Your input: _udp://[REDACTED]:443_
**scripts/welcome.sh: line 109: mapfile: command not found**
Invalid input data format. Please try again..
To use bitscout remotely you will need a VPN server.
Please enter your designated VPN server protocol (udp/tcp), host and port. You can change it later.
Examples:
 udp://127.0.0.1:2222
 tcp://myvpnserver:8080
Your input:`

**Comment by vitaly-kamluk** [comment]
Hi!
Make sure you are trying the latest code version. There is no mapfile command in scripts/welcome.sh at line 109. mapfile comes as a standard command provided by bash and is used in scripts/welcome.sh at line 123.
Please confirm if you are trying the latest version.

**Comment by unstatusthequo** [comment]
Interesting. I downloaded the ZIP on file from the product page just yesterday. I'll try to clone instead.

**Comment by unstatusthequo** [comment]
I cloned it from scratch in terminal and executed automake.sh again. Same result.  It just occurred to me that maybe I need to do this in Linux and not MacOS.  Could that be the issue?

**Comment by vitaly-kamluk** [comment]
Oh, absolutely. Recommended is Ubuntu 18.04 LTS. You may even use LiveCD and build an ISO on a VM booted from LiveCD. See project wiki on Github too.

**Comment by unstatusthequo** [comment]
Ok great to know. Might be something to add to readme for repo for others. ;)
