### ISSUE TITLE
Alternative VPN setup?

### ISSUE THREAD

**Issue by xme** [vitaly-kamluk/bitscout#25]
Hi,
First of all, great tool!
I'm trying to make it connect to another existing VPN solution that uses other interface types (tunX) and other IP address ranges. The VPN connection is established when I boot bitscout but I can't get any connection to it. I see incoming packets at tun0 interface but they seem to be dropped... Any tip?

**Comment by xme** [comment]
Nevermind, I found the issue... nothing related to bitscout but a wrong routing table pushed by the VPN server...

**Comment by vitaly-kamluk** [comment]
Alright, thanks for sharing. I was about to suggest checking the openvpn config too. We use tap interface. If you use tun, I guess you may need to add "dev-type tun" to the openvpn config of bitscout.
