### ISSUE TITLE
Order of menu inverted?

### ISSUE THREAD

**Issue by xme** [vitaly-kamluk/bitscout#27]
Hi,
While working on the "scout-manage" script, I ended with dialog menus that are displayed in reserver order!? I did not change anything related to this part of the code. Any idea of what might happen?
Ex: instead of having: 
INTRODUCTION
NETWORK
DISK
...

The Live CD, once booted, displays:
SHUTDOWN
SHELL
CONTAINER
...
DISK
NETWORK
INTRODUCTION

**Comment by vitaly-kamluk** [comment]
I have noticed the same in Ubutu 20.04. Something has changed in the dialog TUI tool we use. So far it's fixed now, closing the issue...
