### ISSUE TITLE
Custom keyboard settings could be applied to images for better user experience

### ISSUE THREAD

**Issue by ro-olivier** [vitaly-kamluk/bitscout#32]
Hello Vitaly!

As we discussed during the BotConf 2022 workshop, when running the `makebuild.sh` script from a Ubuntu machine that has had its keyboard layout customised, the customisation are not pushed to the image that is built. When booting the BitScout image, both the "guest container" and the "local owner" shells will use the default Ubuntu keyboard layout settings.

I guess one way to handle this issue could be simply to ask a question to the user during the building phase.
The script could check the content of the `/etc/default/keyboard` file and, if it's not the default file, then it notifies the user that is has detected that the build script is being run on a machine with non-default keyboard and may suggest a choice between "using the custom keyboard settings that were found" and "using default keyboard layout".

Then, if the user decides to use the custom keyboard layout, actually doing this is as simple as changing the values found in the `/etc/default/keyboard` files on the BitScout systems. I'm not sure however _where_ in the scripts this should be implemented. Could the `chroot_configure.sh` script work? Would that affect both systems or only the "guest container system"?

Cheers!

**Comment by vitaly-kamluk** [comment]
Sorry to get back to this only now. Seems that there is no need to change anything on Bitscout, it's possible to change keyboard layout to a national one on a running Bitscout with **`loadkeys fr`** command (for French keyboard). Added this hint to the [cheatsheet page](https://bitscout-forensics.info/docs/cheatsheet).

Closing the issue for now.
