### ISSUE TITLE
Unable to boot persistent image from USB

### ISSUE THREAD

**Issue by brightpinefield** [vitaly-kamluk/bitscout#40]
I've been trying to boot a raw persistent image of Bitscout from USB but it isn't working. 

Attached a screenshot from Gparted.. the dd process seemed to complete successfully but I'm not having any luck..  if anyone has made a persistent image of Bitscout on USB, I'd be interested in knowing what was involved to get it to work.  Thanks!

![Bitscout_raw_USB](https://github.com/vitaly-kamluk/bitscout/assets/62759487/99124c51-84de-4b15-b6d9-88c2e18c9337)

**Comment by vitaly-kamluk** [comment]
Hey, first of all, thanks for reporting this and the other issues!

I will get back to the other issues soon, but let's start with this one. Note that the Bitscout image (unless you changed it manually in config/bitscout-build.conf) is hybrid. This means it can boot on older MBR-based systems and UEFI-based systems.

Just now, I have built a raw image with persistence and tested it on a qemu/libvirt VM. It works fine as long as you provide the correct VM settings. I tested both MBR and UEFI boot options. I also transferred the raw disk image to a USB drive and tested it on a physical laptop. It worked for me in both UEFI and MBR boot variants.

Now, looking at your partition table structure, it seems perfectly fine. I have got an equivalent one:
![screenshot_2023-05-25](https://github.com/vitaly-kamluk/bitscout/assets/1012671/8840e7af-8093-4b43-a24c-dafbc9ee4a67)

I would recommend trying the image on a VM first. Make sure you attach it as a raw disk. I might give you some hints if you share which VM software you are using. Once you confirm that it works on a VM, it means it's likely not the image issue, so proceed to check the boot settings on your laptop. Make sure it doesn't get blocked by Secure Boot (it must be off). Explore other boot settings from your laptop vendor. If you have any doubts, take a screenshot and let's figure it out together here. I'm happy to help resolve this issue.

**Comment by brightpinefield** [comment]
Hi Vitaly!  Thank you for your help with this.  I do have VMware Fusion and I'll try to set up a VM to run the raw disk..  If you have some hints for me on this, I'd appreciate them. 

I noticed in your screenshot of your USB disk layout, /dev/sda1 is tagged as "grub2 core.img" under File System.. Mine says "unknown".. wondering if that may be something.. I need to check what the ! warning logos are in my first two devices ..

**Comment by brightpinefield** [comment]
I got it working. I think it had to do with previous partitions being on the destination drive.  I wiped the drive completely and redid the dd image.
