### ISSUE TITLE
Unable to boot using bootable USB

### ISSUE THREAD

**Issue by nkl0x55** [vitaly-kamluk/bitscout#5]
Hi, 

Thanks for this project.
Manage to create the ISO using a Ubuntu Live.

Subsequently create a bootable USB but was unable to boot from it.
![deypuaquwaadlsu](https://user-images.githubusercontent.com/5791182/28047956-5a34fc1e-6620-11e7-9d44-285253979327.jpg)

**Comment by vitaly-kamluk** [comment]
Thanks for submitting this bug. We didn't have time to properly test it on real USB. We got a fix and will release it on Github soon. Testing the fix now.

**Comment by vitaly-kamluk** [comment]
Can you try current latest version? It shall build bootable hybrid USB/CD ISO image. You can transfer it to USB drive on linux with the following command:
sudo dd if=./bitscout-16.04.iso of=/dev/sdX
where /dev/sdX is your USB device. Careful with this command! Do not wipe your hdd accidentally!

**Comment by vitaly-kamluk** [comment]
This issue shall be closed by https://github.com/vitaly-kamluk/bitscout/commit/2f02b0a109d5e3d143c0abea28eb57f075c3d182

**Comment by nkl0x55** [comment]
Hi,

Apologies for the late reply.
Had tested, it's working.

Thanks.
