### ISSUE TITLE
Remote disk acquisition

### ISSUE THREAD

**Issue by aeradius** [vitaly-kamluk/bitscout#6]
Hello,
How to perform a remote disk acquisition from the container to the expert ? 
It is possible to do that by using a "dd" command via ssh ? 
Thanks.

**Comment by vitaly-kamluk** [comment]
Yes, that's one of the basic features. Please see desceiption in https://github.com/vitaly-kamluk/bitscout/wiki/Basic-Usage.

**Comment by aeradius** [comment]
My question was in the case in the expert wants to acquire the disk image (of the  host computer) on his own remote computer ? How to pass throw the container ?

**Comment by vitaly-kamluk** [comment]
Bitscout assumes you have the owner who authorizes disk access to the expert. If you are both owner and the expert, you don't need the container, just enable ssh service on the host, open port 22 in the firewall and disable forwarding it to the container.
You need to modify the following files before building the ISO:  
./resources/sbin/host-iptables
./scripts/chroot_configure_ssh.sh

And that's a good idea to make it simple option in the builder. We will address this in the near future.
