### ISSUE TITLE
Open VPN IP Adresses

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#8]
Hi.
When I build the image and try to set up server all works good.
But I have a question about the IP when I start up from the ISO image.

My Question is, when I start from the iso file the client get an ip=10.0.3.1 when I go to shell and use ifconfig.

I can also ping 10.0.3.2 but no more.
I mean when I boot up the Bitscout ISO file.

I thought will get 10.1.0.2 as in the IP-Pools.lst.

Or have I misunderstood anything?

Dennis

Here is the server config.

ifconfig 10.1.0.1 255.255.255.0

ifconfig-pool 10.1.0.2 10.1.0.250
ifconfig-pool-persist /etc/openvpn/scout/ip_pool.lst 0

tls-server
tls-auth /etc/openvpn/scout/ta.key 0
ca /etc/openvpn/scout/ca.crt
cert /etc/openvpn/scout/scoutserver.crt
key /etc/openvpn/scout/scoutserver.key
dh /etc/openvpn/scout/dh2048.pem

And here is the IP_pools.lst
scout,10.1.0.2
expert,10.1.0.3

**Comment by vitaly-kamluk** [comment]
Dennis, 10.3.0.2 is the expert's container IP.
10.3.0.1 is the host system IP (virtual interface that connects the host and the container).

You are right, your vpn interface IP shall be 10.1.0.2 and the interface name is tap0. If you don't see it, it means the vpn isn't up. 
You need to go to the host shell and see why vpn isn't up.
1. Check that your vpn server is accessible from the host shell (can you ping the server?).
2. Check openvpn log in /var/log/openvpn.scout.log

Let me know how it goes!

**Comment by vitaly-kamluk** [comment]
One more thing: you cannot see 10.1.0.2 from within the container. It is visible only on the host (outside container) and is packets to port 22 of 10.1.0.2 (vpn) are redirected to port 22 of 10.3.0.2 (container) via iptables on the host. You can see iptables rules file in /sbin/host-iptables on the host.

**Comment by melorium** [comment]
Thanks for your input.
I realy like your Software.
Here is the screenshot when I start from the ISO.
No open vpn server started.
the dresses should be 10.3.0.1 and 10.3.0.2 not 10.0.3.1 and 10.0.3.2.
I ping from the shell inside bitscout.
Du you think I did any wrong somewhere.
Or maybe the ip conf from GitHub.

Dennis

![skarmklipp 2017-08-14 14 35 02](https://user-images.githubusercontent.com/31001934/29272003-6c1348e8-80fe-11e7-993a-19d9843b5654.png)
![skarmklipp 2017-08-14 14 38 13](https://user-images.githubusercontent.com/31001934/29272004-6c255a56-80fe-11e7-95ad-6802df52e5e2.png)

**Comment by melorium** [comment]
I don't have any expert running and no vpn server running just the scout iso started.

Dennis

**Comment by melorium** [comment]
Ahhh
Du you think this is the problems on the iso 1.0.3.2 instead of 10.3.0.2
![skarmklipp 2017-08-14 15 20 05](https://user-images.githubusercontent.com/31001934/29273323-258adff2-8104-11e7-8f17-af25d1c3fdbb.png)


Dennis

**Comment by melorium** [comment]
Du you know where on the bitscouts isomaker machine I can find the wrong settings 10.0.3.2 for the creation of sbin/host-iptables on the iso file?

Dennis :)

**Comment by melorium** [comment]
I think I found it in /home/parallels/bitscout/scripts/chroot_create_container.sh
sudo cp -v resources/lxc/config/lxc-net chroot/etc/default/
echo "dhcp-hostsfile=/etc/lxc/dnsmasq-hosts.conf" | sudo tee chroot/etc/lxc/dnsmasq.conf >/dev/null
echo "${PROJECTNAME},10.0.3.2" | sudo tee chroot/etc/lxc/dnsmasq-hosts.conf >/dev/null

Du you think its there?

**Comment by vitaly-kamluk** [comment]
Please check the following diagram and description to better understand current network communication scheme: https://github.com/vitaly-kamluk/bitscout/wiki/Network-Communication
If you create a VPN server everything should work. You can run Bitscout on a local VM and start openvpn server on your system for testing.

**Comment by melorium** [comment]
Thanks A lot.
But I must ask in the script "chroot_create_container.sh" row 33 echo "${PROJECTNAME},10.0.3.2" | sudo tee chroot/etc/lxc/dnsmasq-hosts.conf >/dev/null should it not be 10.3.0.2 there? Or maybe I have wrong ?

**Comment by melorium** [comment]
aaa thanks

**Comment by melorium** [comment]
Thanks now I understand ! :)

**Comment by vitaly-kamluk** [comment]
Let me close this issue now. Should you have other questions feel free to email us at bitscout[at]kaspersky.com or open another issue.
